### ISSUE TITLE
Ruff linting and formatting merge check

### ISSUE THREAD

**Issue by EdwardTheLegend** [ib-ai/ib.py#35]
That would be great too. I think we can set up `pre-commit` to run on commit and add a merge check too just in case. Perhaps we should open a separate issue for further discussion?

_Originally posted by @n0Oo0Oo0b in https://github.com/ib-ai/ib.py/issues/33#issuecomment-2123856467_

**Comment by NathanealV** [comment]
We've decided to use GitHub actions + pull request merge blocks over pre-commit hooks - will update this issue accordingly.
